[build]
  command = "pip install -r requirements.txt"
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200
  force = true

[functions]
  directory = "functions"
